### ISSUE TITLE
Comment and Reformat

### ISSUE THREAD

**Issue by samuelmanzer** [nujarek/htdocs#1]
Start at the top of the file:

https://github.com/nujarek/htdocs/blob/8659d059df207607cc5dcde82d01c956e16c8d3e/styles.css#L1

Mark off the CSS reset section like this 

```
/**** BEGIN: CSS RESET ****/
...
/**** END: CSS RESET ****/
```

After the CSS reset section, put a comment defining your breakpoints

```
/**** BREAKPOINTS ***
* phones: xyz px
* tablet: xyz px
* laptop: xyz px
* desktop: xyz px
*/
```

Then rename `container1` to something more descriptive like `title-container` 

Put comments above each media query indicating the breakpoint to which it refers:

```
/* phones */
```

**Comment by jackmanzer** [comment]
Yo bro, made a number 1 b391d36aad10e865ae06757a5602d41f29bd6f74

**Comment by samuelmanzer** [comment]
Hello there, 

Just circling back on this issue to see if you've moved the needle - want 
to make sure that we are incorporating all best practices and maximizing synergy. 

Let me know if you have the bandwidth for a deep dive to discuss how we can leverage 
the low hanging fruit here - gotta make sure that we are aligned going forward. 

So yeah let's take this offline and get clarity on whether we should put a pin in this 
or finish it in the next sprint. 

Stay fierce and #customerobsessed my dude
